## NumPy

NumPy is a fundamental Python package to efficiently practice data science. In this lesson you will learn to work with powerful tools in the NumPy array, and get started with data exploration.

### Your First NumPy Array

In this chapter, we're going to dive into the world of baseball. Along the way, you'll get comfortable with the basics of ```numpy```, a powerful package to do data science.

A list ```baseball``` has already been defined in the Python script, representing the height of some baseball players in centimeters. Can you add some code here and there to create a numpy array from it?

In [1]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

In [2]:
import utils

# Import the numpy package as np
import numpy as np

In [3]:
# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

In [4]:
# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


### Baseball players' height

You are a huge baseball fan. You decide to call the MLB (Major League Baseball) and ask around for some more statistics on the height of the main players. They pass along data on more than a thousand players, which is stored as a regular Python list: ```height_in```. The height is expressed in inches. Can you make a ```numpy``` array out of it and convert the units to meters?

In [5]:
# Create a numpy array from height: np_height
np_height = np.array(utils.height_in)

In [6]:
# Print out np_height
print(np_height)

[74 74 72 ... 75 75 73]


In [7]:
# Convert np_height to m: np_height_m
np_height_m = np_height * 0.0254 

In [8]:
# Print np_height_m
print(np_height_m)

[1.8796 1.8796 1.8288 ... 1.905  1.905  1.8542]


### Baseball player's BMI

The MLB also offers to let you analyze their weight data. Again, both are available as regular Python lists: ```height_in``` and ```weight_lb```. ```height_in``` is in inches and ```weight_lb``` is in pounds.

It's now possible to calculate the BMI of each baseball player. We will use the following equation:

$$\mathrm{BMI} = \frac{\mathrm{weight (kg)}}{\mathrm{height (m)}^2}$$

In [9]:
# Create array from weight with correct units: np_weight_kg
np_weight_kg = np.array(utils.weight_lb) * 0.453592

In [10]:
# Calculate the BMI: bmi
bmi = np_weight_kg / np_height_m ** 2

In [11]:
# Print out bmi
print(bmi)

[23.11037639 27.60406069 28.48080465 ... 25.62295933 23.74810865
 25.72686361]


### Lightweight baseball players

To subset both regular Python lists and ```numpy``` arrays, you can use square brackets:

```
x = [4 , 9 , 6, 3, 1]
x[1]
import numpy as np
y = np.array(x)
y[1]
```

For ```numpy``` specifically, you can also use boolean ```numpy``` arrays:

```
high = y > 5
y[high]
```

In [12]:
# Create the light array
light = bmi < 21

In [13]:
# Print out light
print(light)

[False False False ... False False False]


In [14]:
# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[20.54255679 20.54255679 20.69282047 20.69282047 20.34343189 20.34343189
 20.69282047 20.15883472 19.4984471  20.69282047 20.9205219 ]


### NumPy Side Effects

```NumPy``` is great for doing vector arithmetic. If you compare its functionality with regular Python lists, however, some things have changed.

First of all, ```numpy``` arrays cannot contain elements with different types. If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. This is known as type coercion.

Second, the typical arithmetic operators, such as ```+```, ```-```, ```*``` and ```/``` have a different meaning for regular Python lists and ```numpy``` arrays.

Have a look at this line of code:

```
np.array([True, 1, 2]) + np.array([3, 4, False])
```

In [15]:
np.array([True, 1, 2])

array([1, 1, 2])

In [16]:
np.array([3, 4, False])

array([3, 4, 0])

In [17]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

### Subsetting NumPy Arrays

You've seen it with your own eyes: Python lists and ```numpy``` arrays sometimes behave differently. Luckily, there are still certainties in this world. For example, subsetting (using the square bracket notation on lists or arrays) works exactly the same:

```
x = ["a", "b", "c"]
x[1]

np_x = np.array(x)
np_x[1]
```

In [18]:
# Print out the weight at index 50
print(np_weight_kg[50])

90.7184


In [19]:
# Print out sub-array of np_height: index 100 up to and including index 110
print(np_height_m[100:111])

[1.8542 1.8796 1.8288 1.8542 1.7526 1.8288 1.8542 1.905  1.905  1.8542
 1.8288]


## 2D NumPy Arrays

### Your First 2D NumPy Array

Before working on the actual MLB data, let's try to create a 2D ```numpy``` array from a small list of lists.

In [20]:
# Create baseball_2d, a list of lists
baseball_2d = [[180, 78.4],
               [215, 102.7],
               [210, 98.5],
               [188, 75.2]]

In [21]:
# Create a 2D numpy array from baseball_2d: np_baseball_2d
np_baseball_2d = np.array(baseball_2d)

In [22]:
# Print out the type of np_baseball_2d
print(type(np_baseball_2d))

<class 'numpy.ndarray'>


In [23]:
# Print out the shape of np_baseball_2d
print(np_baseball_2d.shape)

(4, 2)


### Baseball data in 2D form

You have another look at the MLB data and realize that it makes more sense to restructure all this information in a 2D ```numpy``` array. This array should have 1015 rows, corresponding to the 1015 baseball players you have information on, and 2 columns (for height and weight).

The MLB was, again, very helpful and passed you the data in a different structure, a Python list of lists. In this list of lists, each sublist represents the height and weight of a single baseball player. The name of this embedded list is ```baseball```.

In [24]:
# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(utils.baseball2D)

In [25]:
# Print out the shape of np_baseball
print(np_baseball.shape)

(1015, 2)


### Subsetting 2D NumPy Arrays

If the 2D ```numpy``` array has a regular structure, i.e. each row and column has a fixed number of values, complicated ways of subsetting become very easy. Have a look at the code below where the elements ```"a"``` and ```"c"``` are extracted from a list of lists.

```
# regular list of lists
x = [["a", "b"], ["c", "d"]]
[x[0][0], x[1][0]]

# numpy
import numpy as np
np_x = np.array(x)
np_x[:,0]
```

For regular Python lists, this is a real pain. For 2D ```numpy``` arrays, however, it's pretty intuitive! The indexes before the comma refer to the rows, while those after the comma refer to the columns. The ```:``` is for slicing; in this example, it tells Python to include all rows.

In [26]:
# Print out the 50th row of np_baseball
print(np_baseball[49,:])

[ 70 195]


In [27]:
# Select the entire second column of np_baseball: np_weight
np_weight_lb = np_baseball[:, 1]
print(np_weight_lb)

[180 215 210 ... 205 190 195]


In [28]:
# Print out height of 124th player
print(np_baseball[123,0])

75


### 2D Arithmetic

Remember how you calculated the Body Mass Index for all baseball players? ```numpy``` was able to perform all calculations element-wise (i.e. element by element). For 2D ```numpy``` arrays this isn't any different! You can combine matrices with single numbers, with vectors, and with other matrices:

```
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
np_mat * 2
np_mat + np.array([10, 10])
np_mat + np_mat
```

We managed to get hold of the changes in height, weight and age of all baseball players. It is available as a 2D ```numpy``` array, ```updated```.

In [29]:
np_baseball = np.array(utils.baseball)
np_updated = np.array(utils.updated)

Let's add ```np_baseball``` and ```updated``` and print out the result.

In [30]:
# Print out addition of np_baseball and np_updated
print(np_baseball + np_updated)

[[ 75.2303559  168.83775102  23.99      ]
 [ 75.02614252 231.09732309  35.69      ]
 [ 73.1544228  215.08167641  31.78      ]
 ...
 [ 76.09349925 209.23890778  26.19      ]
 [ 75.82285669 172.21799965  32.01      ]
 [ 73.99484223 203.14402711  28.92      ]]


We want to convert the units of height and weight to metric (meters and kilograms respectively). As a first step, create a ```numpy``` array with three values: ```0.0254```, ```0.453592``` and ```1```.

In [31]:
conversion = np.array([0.0254, 0.453592, 1])

In [32]:
# Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[ 1.8796  81.64656 22.99   ]
 [ 1.8796  97.52228 34.69   ]
 [ 1.8288  95.25432 30.78   ]
 ...
 [ 1.905   92.98636 25.19   ]
 [ 1.905   86.18248 31.01   ]
 [ 1.8542  88.45044 27.92   ]]


## Numpy: Basic Statistics

### Average versus median

You now know how to use ```numpy``` functions to get a better feeling for your data. It basically comes down to importing ```numpy``` and then calling several simple functions on the ```numpy``` arrays:

```
import numpy as np
x = [1, 4, 8, 10, 12]
np.mean(x)
np.median(x)
```

After restructuring the data, however, we notice that some height values are abnormally high. Follow the instructions and discover which summary statistic is best suited if you're dealing with so-called outliers.

In [33]:
np_baseball = np.array(utils.baseball_outliers)

In [34]:
# Create np_height_in from np_baseball
np_height_in = np_baseball[:, 0]

In [35]:
# Print out the mean of np_height
print(np.mean(np_height_in))

1586.4610837438424


In [36]:
# Print out the median of np_height
print(np.median(np_height_in))

74.0


### Explore the baseball data

Because the mean and median are so far apart, you decide to complain to the MLB. They find the error and send the corrected data over to you. It's again available as a 2D Numpy array ```np_baseball```, with three columns.

In [37]:
np_baseball = np.array(utils.baseball)

In [38]:
# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

Average: 73.6896551724138


In [39]:
# Print median height.
med = np.median(np_baseball[:, 0])
print("Median: " + str(med))

Median: 74.0


In [40]:
# Print out the standard deviation on height.
stddev = np.std(np_baseball[:, 0])
print("Standard Deviation: " + str(stddev))

Standard Deviation: 2.312791881046546


Do big players tend to be heavier?

In [41]:
# Print out correlation between first and second column.
corr = np.corrcoef(np_baseball[:, 0], np_baseball[:, 1])
print("Correlation: " + str(corr))

Correlation: [[1.         0.53153932]
 [0.53153932 1.        ]]


## Blend it all together

In the last few exercises you've learned everything there is to know about heights and weights of baseball players. Now it's time to dive into another sport: soccer.

You've contacted FIFA for some data and they handed you two lists. The lists are the following:

```
positions = ['GK', 'M', 'A', 'D', ...]
heights = [191, 184, 185, 180, ...]
```

Each element in the lists corresponds to a player. The first list, positions, contains strings representing each player's position. The possible positions are: ```'GK'``` (goalkeeper), ```'M'``` (midfield), ```'A'``` (attack) and ```'D'``` (defense). The second list, heights, contains integers representing the height of the player in cm. The first player in the lists is a goalkeeper and is pretty tall (191 cm).

You're fairly confident that the median height of goalkeepers is higher than that of other players on the soccer field. Some of your friends don't believe you, so you are determined to show them using the data you received from FIFA and your newly acquired Python skills.

In [42]:
# Import numpy
import numpy as np

In [43]:
# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(utils.positions)
np_heights = np.array(utils.heights)

In [44]:
# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == "GK"]

In [45]:
# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']

In [46]:
# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

Median height of goalkeepers: 188.0


In [47]:
# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

Median height of other players: 181.0
